#!/bin/bash
echo "=== EcoFlow - Environmental Intelligence Center ==="
echo ""
echo "Para iniciar o sistema completo, execute em terminais separados:"
echo ""
echo "  Terminal 1 (API Python):"
echo "    cd api && ./start.sh"
echo ""
echo "  Terminal 2 (Frontend):"
echo "    cd site/geo && ./start.sh"
echo ""
echo "Ou instale as dependencias primeiro:"
echo "    pip install -r api/requirements.txt"
echo ""
echo "URLs:"
echo "  Frontend: http://localhost:8080"
echo "  API:      http://localhost:8000"
echo "  Docs:     http://localhost:8000/docs"
